###
POST http://localhost:9000/api/usuarios HTTP/1.1
Content-Type: application/json

{
    "nombre": "holaaa",
    "edad": "1",
    "gmail": "pepe@gmail.com"
}

###
GET http://localhost:9000/api/usuarios HTTP/1.1

###
GET http://localhost:9000/api/usuarios/662fd35364ed3c7e87919e77 HTTP/1.1

###
PUT http://localhost:9000/api/usuarios/662fd35364ed3c7e87919e77 HTTP/1.1
Content-Type: application/json

{
    "nombre": "Pepe",
    "edad": "24",
    "gmail": "PepeElPro@gmail.com"
}

###
DELETE http://localhost:9000/api/usuarios/662fe90e9ac60658de0ef963 HTTP/1.1
