###
POST http://localhost:9000/api/ropas HTTP/1.1
Content-Type: application/json

{
    "prenda": "pantalon",
    "marca": "adidad",
    "cantidad": "5",
    "color":"negra",
    "precio_por_unidad":"$10000",
    "id":"2"
}

###
GET http://localhost:9000/api/ropas HTTP/1.1

###
GET http://localhost:9000/api/ropas/6631442e6e17428282afaa35 HTTP/1.1

###
PUT http://localhost:9000/api/ropas/2 HTTP/1.1
Content-Type: application/json

{
    "prenda": "pantalon",
    "marca": "adidad",
    "cantidad": "5",
    "color":"negra",
    "precio_por_unidad":"$10000",
    "id":"2"
}

###
DELETE http://localhost:9000/api/ropas/2 HTTP/1.1